version: '3.7'
services:
  frontend:
    container_name: frontend
    stdin_open: true
    build:
      context: frontend
      dockerfile: frontend.Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING= "true"
  backend:
    container_name: backend
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/
      - ./backend.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    container_name: php
    build:
      context: backend
      dockerfile: backend.Dockerfile
    volumes:
    - ./backend:/var/www/